package:
  name: netcdf-c
  version: 4.3.2

source:
  fn: netcdf-4.3.2.tar.gz
  url: ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-4.3.2.tar.gz
  md5: 2fd2365e1fe9685368cd6ab0ada532a0

requirements:
  build:
    - curl
    - hdf5
    - zlib
    - gcc
  run:
    - curl
    - hdf5
    - zlib

about:
  home: http://www.unidata.ucar.edu/software/netcdf/
  license: MIT