package:
  name: mpc
  version: 1.0.1

source:
  fn: mpc-1.0.1.tar.gz
  url: ftp://ftp.gnu.org/gnu/mpc/mpc-1.0.1.tar.gz

requirements:
  build:
    - gmp
    - mpfr
  run:
    - gmp
    - mpfr

about:
  home:
  license: