package:
  name: gcc
  version: 4.8.2

source:
  fn: gcc-4.8.2.tar.bz2
  url: http://mirrors-usa.go-parts.com/gcc/releases/gcc-4.8.2/gcc-4.8.2.tar.bz2

requirements:
  build:
    - gmp
    - mpc
    - mpfr
  run:
    - gmp
    - mpc
    - mpfr

about:
  home:
  license:
