package:
  name: esmpy
  version: HEAD
build: 
  number: 2
source:
  git_url: git://git.code.sf.net/p/esmf/esmf
requirements:
  build:
    - python
    - numpy
    - esmf
  run:
    - python
    - numpy
    - esmf
about:
  summary: https://www.earthsystemcog.org/projects/esmpy/
