package:
  name: mpfr
  version: 3.1.2

source:
  fn: mpfr-3.1.2.tar.bz2
  url: http://www.mpfr.org/mpfr-current/mpfr-3.1.2.tar.bz2

requirements:
  build:
    - gmp
  run:
    - gmp

about:
  home:
  license: